2024-12-30 05:21:44,057 - ERROR - URL Error https://stream-gtlc.telecentro.net.ar/hls/telemaxhls/0/playlist.m3u8: HTTPSConnectionPool(host='stream-gtlc.telecentro.net.ar', port=443): Max retries exceeded with url: /hls/telemaxhls/0/playlist.m3u8 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-12-30 05:21:59,568 - ERROR - URL Error https://bvsat02.cdn.rcs.net.ar/mnp/construiriptv/output.mpd: HTTPSConnectionPool(host='bvsat02.cdn.rcs.net.ar', port=443): Max retries exceeded with url: /mnp/construiriptv/output.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1ea20>, 'Connection to bvsat02.cdn.rcs.net.ar timed out. (connect timeout=15)'))
2024-12-30 05:21:59,593 - ERROR - URL Error https://d3055hobuue3je.cloudfront.net/out/v1/188a8f3baf914a35868453bd5d0b0fd2/index_4.m3u8: HTTPSConnectionPool(host='d3055hobuue3je.cloudfront.net', port=443): Max retries exceeded with url: /out/v1/188a8f3baf914a35868453bd5d0b0fd2/index_4.m3u8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdee0d1faa0>: Failed to resolve 'd3055hobuue3je.cloudfront.net' ([Errno -5] No address associated with hostname)"))
2024-12-30 05:22:14,568 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164881.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:22:37,783 - ERROR - URL Error http://168.197.196.98:9981/stream/channelid/1475050013?profile=pass: HTTPConnectionPool(host='168.197.196.98', port=9981): Max retries exceeded with url: /stream/channelid/1475050013?profile=pass (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d1f3e0>, 'Connection to 168.197.196.98 timed out. (connect timeout=15)'))
2024-12-30 05:22:52,800 - ERROR - URL Error http://168.197.196.98:9981/stream/channelid/1475050013: HTTPConnectionPool(host='168.197.196.98', port=9981): Max retries exceeded with url: /stream/channelid/1475050013 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d1eed0>, 'Connection to 168.197.196.98 timed out. (connect timeout=15)'))
2024-12-30 05:23:09,281 - ERROR - URL Error http://181.191.140.2:8000/play/a0hd/index.m3u8: HTTPConnectionPool(host='181.191.140.2', port=8000): Max retries exceeded with url: /play/a0hd/index.m3u8 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d68710>, 'Connection to 181.191.140.2 timed out. (connect timeout=15)'))
2024-12-30 05:23:09,893 - ERROR - URL Error http://198.27.117.10:8080/Carlos2022/Carlos2022/362546: HTTPConnectionPool(host='198.27.117.10', port=8080): Max retries exceeded with url: /Carlos2022/Carlos2022/362546 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdee0d690d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-30 05:23:24,909 - ERROR - URL Error http://177.128.115.10:8000/play/a0a6/116203: HTTPConnectionPool(host='177.128.115.10', port=8000): Max retries exceeded with url: /play/a0a6/116203 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d69850>, 'Connection to 177.128.115.10 timed out. (connect timeout=15)'))
2024-12-30 05:23:44,242 - ERROR - URL Error http://181.191.140.2:8000/play/a0ir/index.m3u8: HTTPConnectionPool(host='181.191.140.2', port=8000): Max retries exceeded with url: /play/a0ir/index.m3u8 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d1f260>, 'Connection to 181.191.140.2 timed out. (connect timeout=15)'))
2024-12-30 05:24:03,053 - ERROR - URL Error http://177.128.115.10:8000/play/a0a6/116200: HTTPConnectionPool(host='177.128.115.10', port=8000): Max retries exceeded with url: /play/a0a6/116200 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d69ee0>, 'Connection to 177.128.115.10 timed out. (connect timeout=15)'))
2024-12-30 05:24:03,122 - ERROR - URL Error http://198.27.117.10:8080/Carlos2022/Carlos2022/362529: HTTPConnectionPool(host='198.27.117.10', port=8080): Max retries exceeded with url: /Carlos2022/Carlos2022/362529 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdee0d695e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-30 05:24:17,465 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164869.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:24:32,481 - ERROR - URL Error http://168.197.196.98:9981/stream/channelid/369719429?profile=pass&checkedby:alliptvlinks.com: HTTPConnectionPool(host='168.197.196.98', port=9981): Max retries exceeded with url: /stream/channelid/369719429?profile=pass&checkedby:alliptvlinks.com (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d6a300>, 'Connection to 168.197.196.98 timed out. (connect timeout=15)'))
2024-12-30 05:24:48,026 - ERROR - URL Error https://bvsat02.cdn.rcs.net.ar/mnp/elnueve/output.mpd: HTTPSConnectionPool(host='bvsat02.cdn.rcs.net.ar', port=443): Max retries exceeded with url: /mnp/elnueve/output.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1f710>, 'Connection to bvsat02.cdn.rcs.net.ar timed out. (connect timeout=15)'))
2024-12-30 05:24:48,988 - ERROR - URL Error https://stmvideo2.livecastv.com/canal4/canal4/playlist.m3u8: HTTPSConnectionPool(host='stmvideo2.livecastv.com', port=443): Max retries exceeded with url: /canal4/canal4/playlist.m3u8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdee1591340>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-30 05:25:02,163 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164875.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:25:18,940 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c7eds/CronicaTV/SA_Live_dash_enc_2A/CronicaTV.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c7eds/CronicaTV/SA_Live_dash_enc_2A/CronicaTV.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d69490>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:25:33,977 - ERROR - URL Error http://tv.dominiotv.xyz:25461/live/Rolando/Rolando2021/52487.ts: HTTPConnectionPool(host='tv.dominiotv.xyz', port=25461): Max retries exceeded with url: /live/Rolando/Rolando2021/52487.ts (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d69bb0>, 'Connection to tv.dominiotv.xyz timed out. (connect timeout=15)'))
2024-12-30 05:25:47,144 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164878.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:26:30,921 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164879.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:26:58,522 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164873.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:27:12,554 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164876.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:27:26,121 - ERROR - URL Error http://cord-cutter.net:8080/live/j3McKd/673709/164876.m3u8: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-30 05:27:50,318 - ERROR - URL Error http://190.11.130.46/mnp/canal26/output.mpd: HTTPConnectionPool(host='190.11.130.46', port=80): Max retries exceeded with url: /mnp/canal26/output.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d6b260>, 'Connection to 190.11.130.46 timed out. (connect timeout=15)'))
2024-12-30 05:27:50,908 - ERROR - URL Error https://stream-gtlc.telecentro.net.ar/hls/canal26hls/0/playlist.m3u8: HTTPSConnectionPool(host='stream-gtlc.telecentro.net.ar', port=443): Max retries exceeded with url: /hls/canal26hls/0/playlist.m3u8 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-12-30 05:28:06,952 - ERROR - URL Error https://cdn.cvattv.com.ar/live/c6eds/26_TV_HD/SA_Live_dash_enc_2A/26_TV_HD.mpd: HTTPSConnectionPool(host='cdn.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/26_TV_HD/SA_Live_dash_enc_2A/26_TV_HD.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1e210>, 'Connection to cdn.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:28:21,973 - ERROR - URL Error http://tv.dominiotv.xyz:25461/live/Rolando/Rolando2021/52509.ts: HTTPConnectionPool(host='tv.dominiotv.xyz', port=25461): Max retries exceeded with url: /live/Rolando/Rolando2021/52509.ts (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d6a0c0>, 'Connection to tv.dominiotv.xyz timed out. (connect timeout=15)'))
2024-12-30 05:28:39,952 - ERROR - URL Error http://panel.dattalive.com:1935/8250/8250/playlist.m3u8: HTTPConnectionPool(host='panel.dattalive.com', port=1935): Max retries exceeded with url: /8250/8250/playlist.m3u8 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdee0d690a0>, 'Connection to panel.dattalive.com timed out. (connect timeout=15)'))
2024-12-30 05:28:55,386 - ERROR - URL Error https://panel.seo.tv.bo:3337/live/franzbalboa2live.m3u8: HTTPSConnectionPool(host='panel.seo.tv.bo', port=3337): Max retries exceeded with url: /live/franzbalboa2live.m3u8 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d6a930>, 'Connection to panel.seo.tv.bo timed out. (connect timeout=15)'))
2024-12-30 05:28:55,425 - ERROR - URL Error https://tastemade-es8intl-roku.amagi.tv/playlist.m3u8: HTTPSConnectionPool(host='tastemade-es8intl-roku.amagi.tv', port=443): Max retries exceeded with url: /playlist.m3u8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdee0d6b680>: Failed to resolve 'tastemade-es8intl-roku.amagi.tv' ([Errno -2] Name or service not known)"))
2024-12-30 05:28:56,149 - ERROR - URL Error http://cdnh4.iblups.com/hls/irtp.m3u8: HTTPConnectionPool(host='cdnh4.iblups.com', port=80): Max retries exceeded with url: /hls/irtp.m3u8 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fdee0d6bec0>: Failed to resolve 'cdnh4.iblups.com' ([Errno -2] Name or service not known)"))
2024-12-30 05:28:57,585 - ERROR - URL Error http://59c5c86e10038.streamlock.net:1935/6605140/6605140/playlist.m3u8?checkedby:iptvcat.com: HTTPConnectionPool(host='59c5c86e10038.streamlock.net', port=1935): Max retries exceeded with url: /6605140/6605140/playlist.m3u8?checkedby:iptvcat.com (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdee0d6a870>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-30 05:28:59,352 - ERROR - URL Error https://streamconex.com:1936/canalxfn/canalxfn/playlist.m3u8?PlaylistM3UCL: HTTPSConnectionPool(host='streamconex.com', port=1936): Max retries exceeded with url: /canalxfn/canalxfn/playlist.m3u8?PlaylistM3UCL (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdee0d689e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-30 05:29:05,571 - ERROR - URL Error https://stmvideo2.livecastv.com/telestrella/telestrella/playlist.m3u8?PlaylistM3UCL: HTTPSConnectionPool(host='stmvideo2.livecastv.com', port=443): Max retries exceeded with url: /telestrella/telestrella/playlist.m3u8?PlaylistM3UCL (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdee0d6a930>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-30 05:29:16,988 - ERROR - URL Error https://streaming.telered.com.ar/provincial/streaming/mystream.m3u8?PlaylistM3UCL: HTTPSConnectionPool(host='streaming.telered.com.ar', port=443): Max retries exceeded with url: /provincial/streaming/mystream.m3u8?PlaylistM3UCL (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-12-30 05:29:33,496 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c7eds/La_Nacion/SA_Live_dash_enc_2A/La_Nacion.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c7eds/La_Nacion/SA_Live_dash_enc_2A/La_Nacion.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d6bad0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:29:50,223 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/CNN_en_Espanol/SA_Live_dash_enc_2A/CNN_en_Espanol.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/CNN_en_Espanol/SA_Live_dash_enc_2A/CNN_en_Espanol.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d68ce0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:29:54,246 - ERROR - URL Error https://vd01.streaminghd.net.ar:3787/live/jcslppmtlive.m3u8: HTTPSConnectionPool(host='vd01.streaminghd.net.ar', port=3787): Max retries exceeded with url: /live/jcslppmtlive.m3u8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdee0d6bda0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-12-30 05:29:56,680 - ERROR - URL Error https://cnn-cnninternational-1-eu.rakuten.wurl.tv/playlist.m3u8: HTTPSConnectionPool(host='cnn-cnninternational-1-eu.rakuten.wurl.tv', port=443): Max retries exceeded with url: /playlist.m3u8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fdee0d6bfb0>: Failed to resolve 'cnn-cnninternational-1-eu.rakuten.wurl.tv' ([Errno -2] Name or service not known)"))
2024-12-30 05:30:12,010 - ERROR - URL Error https://edge-live16-sl.cvattv.com.ar/live/c6eds/Fox_News/SA_Live_dash_enc/Fox_News.mpd: HTTPSConnectionPool(host='edge-live16-sl.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Fox_News/SA_Live_dash_enc/Fox_News.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1ec30>, 'Connection to edge-live16-sl.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:30:12,251 - ERROR - URL Error https://tv-trtworld.live.trt.com.tr:443/master_720.m3u8: HTTPSConnectionPool(host='tv-trtworld.live.trt.com.tr', port=443): Max retries exceeded with url: /master_720.m3u8 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))
2024-12-30 05:30:27,448 - ERROR - URL Error https://cdn.cvattv.com.ar/live/c6eds/Euronews/SA_Live_dash_enc/Euronews.mpd: HTTPSConnectionPool(host='cdn.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Euronews/SA_Live_dash_enc/Euronews.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1f410>, 'Connection to cdn.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:30:44,252 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/RAI/SA_Live_dash_enc_2A/RAI.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/RAI/SA_Live_dash_enc_2A/RAI.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1efc0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:31:00,142 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c7eds/Paraguay_TV/SA_Live_dash_enc_2A/Paraguay_TV.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c7eds/Paraguay_TV/SA_Live_dash_enc_2A/Paraguay_TV.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d6b5c0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:31:16,500 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/Canal_de_las_estrellas/SA_Live_dash_enc_2A/Canal_de_las_estrellas.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Canal_de_las_estrellas/SA_Live_dash_enc_2A/Canal_de_las_estrellas.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d68c20>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:31:31,567 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c7eds//Telemundo_HD/SA_Live_dash_enc_2A/Telemundo_HD.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c7eds//Telemundo_HD/SA_Live_dash_enc_2A/Telemundo_HD.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d68c50>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:31:47,247 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c3eds/DiscoveryHomeHealthHD/SA_Live_dash_enc_2A/DiscoveryHomeHealthHD.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c3eds/DiscoveryHomeHealthHD/SA_Live_dash_enc_2A/DiscoveryHomeHealthHD.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d68b90>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:32:02,266 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/TLC/SA_Live_dash_enc_2A/TLC.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/TLC/SA_Live_dash_enc_2A/TLC.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d697c0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:32:17,285 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c7eds/Hola_TV/SA_Live_dash_enc_2A/Hola_TV.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c7eds/Hola_TV/SA_Live_dash_enc_2A/Hola_TV.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d69ee0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:32:33,219 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/TBS/SA_Live_dash_enc_2A/TBS.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/TBS/SA_Live_dash_enc_2A/TBS.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d69eb0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:32:48,571 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/Mas_Chic/SA_Live_dash_enc_2A/Mas_Chic.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Mas_Chic/SA_Live_dash_enc_2A/Mas_Chic.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d69340>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:33:03,602 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/E_Entertainment_Television/SA_Live_dash_enc_2A/E_Entertainment_Television.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/E_Entertainment_Television/SA_Live_dash_enc_2A/E_Entertainment_Television.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1fef0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:33:18,621 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/Food_Network/SA_Live_dash_enc_2A/Food_Network.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Food_Network/SA_Live_dash_enc_2A/Food_Network.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1f6e0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:33:33,638 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c3eds/Gourmet/SA_Live_dash_enc_2A/Gourmet.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c3eds/Gourmet/SA_Live_dash_enc_2A/Gourmet.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0b388f0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:33:49,417 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/Lifetime/SA_Live_dash_enc_2A/Lifetime.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Lifetime/SA_Live_dash_enc_2A/Lifetime.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d68f80>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:34:05,125 - ERROR - URL Error https://cdn.cvattv.com.ar/live/c7eds/Home_and_Garden/SA_Live_dash_enc/Home_and_Garden.mpd: HTTPSConnectionPool(host='cdn.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c7eds/Home_and_Garden/SA_Live_dash_enc/Home_and_Garden.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d6b3b0>, 'Connection to cdn.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:34:20,153 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/EWTN/SA_Live_dash_enc_2A/EWTN.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/EWTN/SA_Live_dash_enc_2A/EWTN.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d69640>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:34:35,172 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/Canal_21/SA_Live_dash_enc_2A/Canal_21.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Canal_21/SA_Live_dash_enc_2A/Canal_21.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d68aa0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:34:51,807 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/MTV_HD/SA_Live_dash_enc_2A/MTV_HD.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/MTV_HD/SA_Live_dash_enc_2A/MTV_HD.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1e090>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:35:07,801 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c7eds/MTV00/SA_Live_dash_enc_2A/MTV00.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c7eds/MTV00/SA_Live_dash_enc_2A/MTV00.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0b38140>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:35:25,253 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/MTV_Hits/SA_Live_dash_enc_2A/MTV_Hits.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/MTV_Hits/SA_Live_dash_enc_2A/MTV_Hits.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d1ea50>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:35:26,255 - ERROR - URL Error https://stream-gtlc.telecentro.net.ar/hls/latinatvhls/main.m3u8: HTTPSConnectionPool(host='stream-gtlc.telecentro.net.ar', port=443): Max retries exceeded with url: /hls/latinatvhls/main.m3u8 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-12-30 05:35:41,274 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/Quiero_HD/SA_Live_dash_enc_2A/Quiero_HD.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Quiero_HD/SA_Live_dash_enc_2A/Quiero_HD.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d69250>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:35:56,794 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/CM/SA_Live_dash_enc_2A/CM.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/CM/SA_Live_dash_enc_2A/CM.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d69d60>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:36:11,813 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/HTV/SA_Live_dash_enc_2A/HTV.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/HTV/SA_Live_dash_enc_2A/HTV.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee1a17770>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:36:26,840 - ERROR - URL Error https://chromecast.cvattv.com.ar/live/c6eds/Vorterix/SA_Live_dash_enc_2A/Vorterix.mpd: HTTPSConnectionPool(host='chromecast.cvattv.com.ar', port=443): Max retries exceeded with url: /live/c6eds/Vorterix/SA_Live_dash_enc_2A/Vorterix.mpd (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0b382c0>, 'Connection to chromecast.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:36:27,400 - ERROR - URL Error https://stream-gtlc.telecentro.net.ar/hls/musictophls/main.m3u8: HTTPSConnectionPool(host='stream-gtlc.telecentro.net.ar', port=443): Max retries exceeded with url: /hls/musictophls/main.m3u8 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-12-30 05:36:50,227 - ERROR - URL Error https://musicsrc.cvattv.com.ar/RDIS: HTTPSConnectionPool(host='musicsrc.cvattv.com.ar', port=443): Max retries exceeded with url: /RDIS (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdee0d6ab70>, 'Connection to musicsrc.cvattv.com.ar timed out. (connect timeout=15)'))
2024-12-30 05:36:59,650 - ERROR - URL Error https://streaming1.locucionar.com/proxy/radiochubut?mp=/stream: ('Connection aborted.', BadStatusLine('RPC-ERR authentication failed\n'))
