2025-05-16 05:48:23,130 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 05:49:58,687 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112660: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:50:15,737 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112664: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:50:32,647 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112665: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:50:48,340 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112666: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:51:05,915 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112667: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:51:22,852 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112668: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:51:39,766 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112669: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:51:55,312 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112670: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:52:11,025 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112671: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:52:27,950 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112672: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:52:43,503 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112673: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:53:00,411 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112674: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:53:17,208 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112675: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:53:34,107 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112676: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:53:51,032 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112677: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:54:06,590 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112678: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:54:23,601 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112679: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:54:39,150 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112680: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:54:56,061 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112681: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:55:11,620 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112682: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:55:28,532 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112683: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:55:45,453 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112684: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:56:02,371 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112685: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:56:19,287 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112686: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:56:34,844 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112687: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:56:51,904 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112688: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:57:08,819 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112689: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:57:24,368 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112690: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:57:41,303 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112691: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:57:58,227 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112692: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:58:13,783 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112693: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 05:58:30,697 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112694: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 05:58:30,775 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f762450>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:30,850 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f763440>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:30,929 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7613a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,007 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f763fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,083 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7da2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,161 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7d9ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,240 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7629f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,315 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f761820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,390 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f763200>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,464 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7638f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,543 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7db410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,618 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7daf60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,697 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f761400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,776 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7638c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,854 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f762420>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:31,929 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f763e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:32,008 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7d8920>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:32,086 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7d8fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:32,521 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 05:58:32,884 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
2025-05-16 05:58:32,962 - ERROR - Request Error http://15.235.15.230:14487/: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f763920>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:33,682 - WARNING - URL Error https://cdn-3.nxplay.com.br/GLOBO_SP_TK/tracks-v1a1/mono.m3u8: Status Code 403
2025-05-16 05:58:34,048 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 05:58:34,412 - INFO - URL OK: http://hls1.sua.tv:80/live/globosphd/s.m3u8
2025-05-16 05:58:34,699 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/90059.m3u8: Status Code 404
2025-05-16 05:58:34,877 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/91431.m3u8: Status Code 404
2025-05-16 05:58:35,098 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/90034.m3u8: Status Code 404
2025-05-16 05:58:35,281 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91421.m3u8: Status Code 404
2025-05-16 05:58:35,486 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91435.m3u8: Status Code 404
2025-05-16 05:58:35,670 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91463.m3u8: Status Code 404
2025-05-16 05:58:35,864 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/90064.m3u8: Status Code 404
2025-05-16 05:58:36,057 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/90019.m3u8: Status Code 404
2025-05-16 05:58:36,252 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/95441.m3u8: Status Code 404
2025-05-16 05:58:36,435 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91405.m3u8: Status Code 404
2025-05-16 05:58:36,629 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91413.m3u8: Status Code 404
2025-05-16 05:58:36,810 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/120082.m3u8: Status Code 404
2025-05-16 05:58:37,006 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91443.m3u8: Status Code 404
2025-05-16 05:58:37,196 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91445.m3u8: Status Code 404
2025-05-16 05:58:37,388 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/95483.m3u8: Status Code 404
2025-05-16 05:58:37,570 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/97396.m3u8: Status Code 404
2025-05-16 05:58:37,766 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91456.m3u8: Status Code 404
2025-05-16 05:58:37,949 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91460.m3u8: Status Code 404
2025-05-16 05:58:38,146 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/95448.m3u8: Status Code 404
2025-05-16 05:58:38,370 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91461.m3u8: Status Code 404
2025-05-16 05:58:38,544 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91467.m3u8: Status Code 404
2025-05-16 05:58:38,733 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91470.m3u8: Status Code 404
2025-05-16 05:58:38,913 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91471.m3u8: Status Code 404
2025-05-16 05:58:39,118 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91473.m3u8: Status Code 404
2025-05-16 05:58:39,296 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91477.m3u8: Status Code 404
2025-05-16 05:58:39,473 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91479.m3u8: Status Code 404
2025-05-16 05:58:39,551 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7633e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:39,627 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7615b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:39,705 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3ff6abd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:39,783 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7db5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:39,859 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7d92e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:39,937 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7db4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,016 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f762570>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,091 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7635c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,166 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f762600>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,240 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f85e4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,319 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f6006b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,394 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f763110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,473 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f762ae0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,552 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f763590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,630 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7d8650>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,705 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f600110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,784 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f601370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:40,862 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b3f7daff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 05:58:41,229 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 05:58:41,575 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
